<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SPORTACUS_FRONT</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="NHibernate" Version="5.6.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportacusGen.ApplicationCore\SportacusGen.ApplicationCore.csproj" />
    <ProjectReference Include="..\SportacusGen.Infraestructure\SportacusGen.Infraestructure.csproj" />
  </ItemGroup>

</Project>
